language: java # to trigger the build on a 'jvm-otp' travis worker
env:
  - PLAY_VERSION=1.2.5
before_script: 
  - wget http://download.playframework.org/releases/play-${PLAY_VERSION}.zip
  - unzip -q play-${PLAY_VERSION}.zip 
script: play-${PLAY_VERSION}/play test ./play-src
notifications:
  # Email notifications are disabled to not annoy anybody.
  # See http://about.travis-ci.org/docs/user/build-configuration/ to learn more
  # about configuring notification recipients and more.
  email: false
